# –û–ø–∏—Å–∞–Ω–∏–µ:
# –í–µ–±-–∏–Ω—Ç–µ—Ä—Ñ–µ–π—Å –¥–æ—Å—Ç—É–ø–µ–Ω –ø–æ –∞–¥—Ä–µ—Å—É http://192.168.1.1:9090/ui
# –ü—Ä–∏ –∏—Å–ø–æ–ª—å–∑–æ–≤–∞–Ω–∏–∏ —Å XKeen —Ä–µ–∫–æ–º–µ–Ω–¥—É–µ—Ç—Å—è –≤—ã–ø–æ–ª–Ω–∏—Ç—å –∫–æ–º–∞–Ω–¥—É "xkeen -ap 80,443,8443,596:599,1400,2000-2300,3478,5222,19200-19400,46420,50000-51000" –≤ SSH —Ç–µ—Ä–º–∏–Ω–∞–ª–µ —Ä–æ—É—Ç–µ—Ä–∞.

log-level: silent
allow-lan: true
tproxy-port: 5000
ipv6: true
mode: rule
external-controller: 0.0.0.0:9090
external-ui: zashboard
external-ui-url: https://github.com/Zephyruso/zashboard/releases/latest/download/dist.zip
profile:
  store-selected: true

sniffer:
  enable: true
  parse-pure-ip: true
  force-dns-mapping: true
  sniff:
    HTTP:
      ports: [80]
    TLS:
      ports: [443]
    QUIC:
      ports: [443]

proxy-groups:
  - name: –ó–∞–±–ª–æ–∫. —Å–µ—Ä–≤–∏—Å—ã
    type: url-test # –ê–≤—Ç–æ–≤—ã–±–æ—Ä —Å–µ—Ä–≤–µ—Ä–∞ —Å –º–∏–Ω–∏–º–∞–ª—å–Ω—ã–º –ø–∏–Ω–≥–æ–º
    url: http://cp.cloudflare.com/ # URL –¥–ª—è —Ç–µ—Å—Ç–∏—Ä–æ–≤–∞–Ω–∏—è
    interval: 300  # –ò–Ω—Ç–µ—Ä–≤–∞–ª –ø—Ä–æ–≤–µ—Ä–∫–∏ (—Å–µ–∫)
    icon: https://cdn.jsdelivr.net/gh/Koolson/Qure@master/IconSet/Color/Reject.png
    include-all: true
    exclude-filter: üá∑üá∫|üá∞üáø|üá∫üá¶

  - name: YouTube
    type: select
    icon: https://cdn.jsdelivr.net/gh/Koolson/Qure@master/IconSet/Color/YouTube.png
    include-all: true
    proxies:
      - –ó–∞–±–ª–æ–∫. —Å–µ—Ä–≤–∏—Å—ã
      - DIRECT

  - name: Discord
    type: select
    icon: https://cdn.jsdelivr.net/gh/Koolson/Qure@master/IconSet/Color/Discord.png
    include-all: true
    proxies:
      - –ó–∞–±–ª–æ–∫. —Å–µ—Ä–≤–∏—Å—ã
      - DIRECT

  - name: Twitch
    type: select
    icon: https://cdn.jsdelivr.net/gh/Koolson/Qure@master/IconSet/Color/Twitch.png
    include-all: true
    proxies:
      - DIRECT
      - –ó–∞–±–ª–æ–∫. —Å–µ—Ä–≤–∏—Å—ã

  - name: –ö–∏–Ω–æ—Ç–µ–∞—Ç—Ä—ã
    type: select
    icon: https://github.com/amatol/xkeen-configuration/raw/refs/heads/main/group-icons/kino.png
    include-all: true
    proxies:
      - –ó–∞–±–ª–æ–∫. —Å–µ—Ä–≤–∏—Å—ã
      - DIRECT

  - name: Meta
    type: select
    icon: https://github.com/zxc-rv/assets/raw/refs/heads/main/group-icons/meta.png
    include-all: true
    proxies:
      - –ó–∞–±–ª–æ–∫. —Å–µ—Ä–≤–∏—Å—ã
      - DIRECT

  - name: Spotify
    type: select
    icon: https://cdn.jsdelivr.net/gh/Koolson/Qure@master/IconSet/Color/Spotify.png
    include-all: true
    proxies:
      - –ó–∞–±–ª–æ–∫. —Å–µ—Ä–≤–∏—Å—ã
      - DIRECT

  - name: Telegram
    type: select
    icon: https://cdn.jsdelivr.net/gh/Koolson/Qure@master/IconSet/Color/Telegram.png
    include-all: true
    proxies:
      - DIRECT
      - –ó–∞–±–ª–æ–∫. —Å–µ—Ä–≤–∏—Å—ã

  - name: Community
    type: select
    icon: https://github.com/amatol/xkeen-configuration/raw/refs/heads/main/group-icons/community.png
    include-all: true
    proxies:
      - –ó–∞–±–ª–æ–∫. —Å–µ—Ä–≤–∏—Å—ã
      - DIRECT

  - name: Cloudflare
    type: select
    icon: https://cdn.jsdelivr.net/gh/Koolson/Qure@master/IconSet/Color/Cloudflare.png
    include-all: true
    proxies:
      - PASS
      - –ó–∞–±–ª–æ–∫. —Å–µ—Ä–≤–∏—Å—ã

  - name: AI
    type: select
    icon: https://cdn.jsdelivr.net/gh/Koolson/Qure@master/IconSet/Color/Bot.png
    include-all: true
    proxies:
      - –ó–∞–±–ª–æ–∫. —Å–µ—Ä–≤–∏—Å—ã

  - name: Twitter
    type: select
    icon: https://cdn.jsdelivr.net/gh/Koolson/Qure@master/IconSet/Color/Twitter.png
    include-all: true
    proxies:
      - –ó–∞–±–ª–æ–∫. —Å–µ—Ä–≤–∏—Å—ã
      - DIRECT

  - name: TikTok
    type: select
    icon: https://github.com/amatol/xkeen-configuration/raw/refs/heads/main/group-icons/tiktok.png
    include-all: true
    proxies:
      - –ó–∞–±–ª–æ–∫. —Å–µ—Ä–≤–∏—Å—ã
      - DIRECT

  - name: QUIC
    type: select
    icon: https://github.com/zxc-rv/assets/raw/refs/heads/main/group-icons/quic.png
    proxies:
      - REJECT
      - PASS
      
# –ü–æ–¥–∫–ª—é—á–µ–Ω–∏–µ —Å –∏—Å–ø–æ–ª—å–∑–æ–≤–∞–Ω–∏–µ–º –ø–æ–¥–ø–∏—Å–∫–∏
proxy-providers:
  proxy-sub:
    type: http
    url: #–¢–£–¢_–°–°–´–õ–ö–ê_–ù–ê_–í–ê–®–£_–ü–û–î–ü–ò–°–ö–£
    path: ./proxy-providers/subscription.yaml
    interval: 3600
    health-check:
      enable: true
      url: http://cp.cloudflare.com/
      interval: 300
      timeout: 2000
      lazy: false
      expected-status: 204
    override:
      udp: true
      tfo: true

rule-providers:
  refilter-domains:
    type: http
    behavior: domain
    format: mrs
    url: https://github.com/legiz-ru/mihomo-rule-sets/raw/main/re-filter/domain-rule.mrs
    path: ./rule-providers/refilter-domains.mrs

  kino:
    type: http
    behavior: domain
    format: mrs
    url: https://github.com/amatol/xkeen-configuration/raw/refs/heads/main/rules/kino.mrs
    path: ./rule-providers/kino-domains.mrs

  tiktok:
    type: http
    behavior: domain
    format: mrs
    url: https://github.com/MetaCubeX/meta-rules-dat/raw/refs/heads/meta/geo/geosite/tiktok.mrs
    path: ./rule-providers/tiktok-domains.mrs

  community:
    type: http
    behavior: domain
    format: mrs
    url: https://github.com/amatol/xkeen-configuration/raw/refs/heads/main/rules/community.mrs
    path: ./rule-providers/community-domains.mrs

  cloudflare-ips:
    type: http
    behavior: ipcidr
    format: mrs
    url: https://github.com/MetaCubeX/meta-rules-dat/raw/refs/heads/meta/geo/geoip/cloudflare.mrs
    path: ./rule-providers/cloudflare-ips.mrs
    interval: 86400

  discord:
    type: inline
    behavior: classical
    format: text
    payload:
      - AND,((DOMAIN-KEYWORD,discord),(NOT,((DOMAIN-SUFFIX,ru))))
      - AND,((RULE-SET,cloudflare-ips,no-resolve),(NETWORK,TCP),(OR,((DST-PORT,2000-2300),(DST-PORT,8443))))
      - AND,((RULE-SET,cloudflare-ips,no-resolve),(NETWORK,UDP),(OR,((DST-PORT,19200-19400),(DST-PORT,50000-51000))))
      - AND,((IP-CIDR,5.200.14.128/25,no-resolve),(NETWORK,UDP),(DST-PORT,50000-51000))
      - AND,((IP-CIDR,34.0.0.0/15,no-resolve),(NETWORK,UDP),(DST-PORT,50000-51000))
      - AND,((IP-CIDR,34.2.0.0/15,no-resolve),(NETWORK,UDP),(DST-PORT,50000-51000))
      - AND,((IP-CIDR,35.192.0.0/11,no-resolve),(NETWORK,UDP),(DST-PORT,50000-51000))
      - AND,((IP-CIDR,66.22.192.0/18,no-resolve),(NETWORK,UDP),(DST-PORT,50000-51000))
      - AND,((IP-CIDR,138.128.136.0/21,no-resolve),(NETWORK,UDP),(DST-PORT,50000-51000))

  telegram-ips:
    type: http
    behavior: ipcidr
    format: mrs
    url: https://github.com/MetaCubeX/meta-rules-dat/raw/refs/heads/meta/geo/geoip/telegram.mrs
    path: ./rule-providers/telegram-ips.mrs
    interval: 86400

  meta-ips:
    type: http
    behavior: ipcidr
    format: mrs
    url: https://github.com/zxc-rv/assets/raw/refs/heads/main/rules/meta-ips.mrs
    path: ./rule-providers/meta-ips.mrs
    interval: 86400

rules:
  - AND,((DST-PORT,443),(NETWORK,UDP)),QUIC
  - OR,((DOMAIN-SUFFIX,gql.twitch.tv),(DOMAIN-SUFFIX,usher.ttvnw.net)),–ó–∞–±–ª–æ–∫. —Å–µ—Ä–≤–∏—Å—ã # –†–∞–∑–±–ª–æ–∫–∏—Ä–æ–≤–∫–∞ –≤—ã—Å–æ–∫–æ–≥–æ –∫–∞—á–µ—Å—Ç–≤–∞ –Ω–∞ Twitch.tv
  - GEOSITE,category-ai-!cn,AI
  - GEOSITE,spotify,Spotify
  - OR,((GEOSITE,youtube),(DOMAIN-SUFFIX,googleusercontent.com)),YouTube
  - GEOSITE,twitch,Twitch
  - GEOSITE,twitter,Twitter
  - RULE-SET,discord,Discord
  - OR,((GEOSITE,meta),(RULE-SET,meta-ips,no-resolve)),Meta
  - OR,((GEOSITE,telegram),(RULE-SET,telegram-ips,no-resolve)),Telegram
  - OR,((GEOSITE,cloudflare),(RULE-SET,cloudflare-ips)),Cloudflare
  - RULE-SET,kino,–ö–∏–Ω–æ—Ç–µ–∞—Ç—Ä—ã
  - RULE-SET,community,Community
  - RULE-SET,tiktok,TikTok
  - RULE-SET,refilter-domains,–ó–∞–±–ª–æ–∫. —Å–µ—Ä–≤–∏—Å—ã
  - MATCH,DIRECT
